# Generated by Django 3.2.4 on 2023-07-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadistica',
            old_name='nombre_estadisitca',
            new_name='nombre_estadistca',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='Posicion',
            new_name='posicion',
        ),
    ]
