# Generated by Django 3.2.4 on 2023-07-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_imageshome_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageshome',
            name='activado',
            field=models.BooleanField(default=False),
        ),
    ]
