# Generated by Django 3.2.4 on 2023-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='club',
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.CharField(default='', max_length=50),
        ),
    ]
