# Generated by Django 3.2.4 on 2023-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0002_auto_20230701_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha_partido',
            field=models.DateTimeField(),
        ),
    ]
