# Generated by Django 3.2.4 on 2023-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0003_alter_partido_fecha_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='activado',
            field=models.BooleanField(default=False),
        ),
    ]
