# Generated by Django 3.2.4 on 2023-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0004_partido_activado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='imagen_escudo',
            new_name='imagen_escudo_local',
        ),
        migrations.AddField(
            model_name='partido',
            name='imagen_escudo_visitante',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
