# Generated by Django 3.2.4 on 2023-07-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0005_auto_20230702_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='numero',
            field=models.PositiveIntegerField(default=0, max_length=2),
        ),
    ]
