# Generated by Django 3.2.4 on 2023-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0006_formacion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='es_local',
            field=models.BooleanField(default=False),
        ),
    ]
