# Generated by Django 3.2.4 on 2023-07-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partido', '0007_formacion_es_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
